name: Update Coin Listing Alerts

on:
  repository_dispatch:  # Allows IFTTT to trigger this workflow
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write

jobs:
  update_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout Repository
        uses: actions/checkout@v3

      - name: ⚙️ Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: 📦 Install Dependencies
        run: pip install requests

      - name: 🔑 Verify GitHub Secrets
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GOOGLE_SHEET_API: ${{ secrets.GOOGLE_SHEET_API }}
        run: |
          if [ -z "${DISCORD_WEBHOOK_URL}" ]; then
            echo "❌ DISCORD_WEBHOOK_URL is missing!"
            exit 1
          fi
          if [ -z "${GOOGLE_SHEET_API}" ]; then
            echo "❌ GOOGLE_SHEET_API is missing!"
            exit 1
          fi

      - name: 🏗 Run Alert Fetching Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GOOGLE_SHEET_API: ${{ secrets.GOOGLE_SHEET_API }}
        run: python fetch_alerts.py

      - name: 📤 Commit & Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add coin_listing_alerts.json
          git diff --cached --quiet || git commit -m "🔄 Update Coin Listing Alerts"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git main

      - name: 🚀 Trigger GitHub Pages Rebuild
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/pages/builds
