name: Fetch Discord Alerts & Update JSON

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allow manual runs

jobs:
  update_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests

      - name: Fetch Discord Alerts
        run: python fetch_alerts.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add coin_listing_alerts.json
          git commit -m "Updated coin listing alerts"
          git push
